server4:
  listen:
    - "%ens2"
  plugins:
    - server_id: 172.16.0.254
    - dns: 172.16.0.254
    - router: 172.16.0.254
    - netmask: 255.255.255.0
    - coresmd: https://demo.openchami.cluster:8443 http://172.16.0.254:8081 /root_ca/root_ca.crt 30s 1h
    - bootloop: /tmp/coredhcp.db default 5m 172.16.0.200 172.16.0.250