#!/bin/bash

CLIENT="${1}"
SERVICE="hsm"

TOKENSMITH_BOOTSTRAP_TOKEN=$(podman exec -e SERVICE=$SERVICE -e CLIENT=$CLIENT tokensmith /bin/sh -c "\
                        /usr/local/bin/tokensmith bootstrap-token create \
                        --bootstrap-store /tmp/tokensmith/bootstrap \
                        --subject \${CLIENT} \
                        --audience \${SERVICE} \
                        --scopes "read" \
                        --output-format json | jq -r '.bootstrap_token'
                        ")

SECRET_NAME="${CLIENT}-bootstrap-token"
printf '%s' "$TOKENSMITH_BOOTSTRAP_TOKEN" | podman secret rm ${SECRET_NAME} 2>/dev/null || true
printf '%s' "$TOKENSMITH_BOOTSTRAP_TOKEN" | podman secret create ${SECRET_NAME} -